[tools]
age = "1.3.1" # renovate: repository=FiloSottile/age
bat = "0.26.1" # renovate: repository=sharkdp/bat
bun = "1.3.6"
delta = "0.18.2" # renovate: repository=dandavison/delta
deno = "2.6.4"
fd = "10.3.0" # renovate: repository=sharkdp/fd
fx = "39.2.0" # renovate: repository=antonmedv/fx
fzf = "0.67.0" # renovate: repository=junegunn/fzf
jq = "1.8.1" # renovate: repository=jqlang/jq
k9s = "0.50.18" # renovate: repository=derailed/k9s
kubectl = "1.35.0" # renovate: datasource=github-tags repository=kubernetes/kubectl
lazygit = "0.58.1" # renovate: repository=jesseduffield/lazygit
lsd = "1.2.0" # renovate: repository=lsd-rs/lsd
node = "22" # renovate: datasource=node-version
ripgrep = "14.1.1" # renovate: repository=BurntSushi/ripgrep
sops = "3.11.0" # renovate: repository=getsops/sops
starship = "1.24.2" # renovate: repository=starship/starship
stern = "1.33.1" # renovate: repository=stern/stern
usage = "2.11.0" # renovate: repository=jdx/usage
uv = "0.9.24" # renovate: repository=astral-sh/uv
vivid = "0.10.1" # renovate: repository=sharkdp/vivid
zoxide = "0.9.8" # renovate: repository=ajeetdsouza/zoxide

"pipx:b2" = "4.5.0"
"pipx:aider-chat" = { version = "0.86.1", uvx_args = "--python python3.12" }
